---
- name: Setup dotfiles by symlinking
  hosts: localhost
  vars:
    conf_files:
      - src: "{{ lookup('env', 'PWD') }}/vim/.vimrc"
        dest: "{{ ansible_env.HOME }}/.vimrc"
      - src: "{{ lookup('env', 'PWD') }}/screen/.screenrc"
        dest: "{{ ansible_env.HOME }}/.screenrc"
      - src: "{{ lookup('env', 'PWD') }}/tmux/.tmux.conf.local"
        dest: "{{ ansible_env.HOME }}/.tmux.conf.local"
  tasks:

    - name: put each configuration files in place
      file:
        src: "{{ item.src }}"
        path: "{{ item.dest }}"
        state: link
      loop: "{{ conf_files }}"

    - include_tasks: vim.yml
    - include_tasks: tmux.yml
