---
- name: Setup dotfiles by symlinking
  hosts: localhost
  vars:
    home_dir: "{{ lookup('env', 'HOME') }}"
    conf_files:
      - src: "{{ playbook_dir }}/vim/.vimrc"
        dest: "{{ home_dir }}/.vimrc"
      - src: "{{ playbook_dir }}/screen/.screenrc"
        dest: "{{ home_dir }}/.screenrc"
#      - src: "{{ playbook_dir }}/tmux/.tmux.conf.local"
#        dest: "{{ home_dir }}/.tmux.conf.local"
  tasks:

    - name: put each configuration files in place
      file:
        src: "{{ item.src }}"
        path: "{{ item.dest }}"
        state: link
      loop: "{{ conf_files }}"

    - include_tasks: vim.yml
#    - include_tasks: tmux.yml
